### ISSUE TITLE
Namespaces Support

### ISSUE THREAD

**Issue by santiagodoldan** [jackdempsey/sequel_polymorphic#14]
is it possible to override the default prefix_type value? We are building a gem which includes different models of our main app, but those models are under a new namespace.

This is the problem we are having:

```ruby
module GemNamespace
  class Preference < Sequel::Model
    many_to_one :configurable, polymorphic: true
  end
end

module GemNamespace
  class Account < Sequel::Model
    one_to_many :preferences, as: :configurable, type: 'Account'
  end
end
```
The default value of prefix_type is equal to "GemNamespace::Account" and I want just "Account".

does it make sense?

**Comment by kuraga** [comment]
@santiagodoldan,
Value of column named `"#{as}_type"` is a class (model) name.
How can we understand the class if we omit namespace?

**Comment by santiagodoldan** [comment]
good point, maybe as the association is already under the "GemNamspace" namespace, it could be possible to build the class anyway. I will think a workaround for this problem we are having.

Thanks
