### ISSUE TITLE
Error on non integer ids

### ISSUE THREAD

**Issue by brauliobo** [jackdempsey/sequel_polymorphic#15]
If the foreign_key is not an integer the query generated won't be valid:
```
     Sequel::DatabaseError:
       PG::UndefinedFunction: ERROR:  operator doesn't exist: text = integer
       LINE 1: ... 'User') AND ("user_comments"."object_id" = 14011))                                                                 ^
```

**Comment by kuraga** [comment]
@brauliobo what's `14011` here?

**Comment by brauliobo** [comment]
the primary key of the object

the issue is triggered when different are used, is it possible to do a type casting?

in the end this turned out to be a missing configuration of the correct primary key on the association, so I'm closing this.
