### ISSUE TITLE
possible to get "uninitialized constant" errors

### ISSUE THREAD

**Issue by jmay** [jackdempsey/sequel_polymorphic#7]
In your README example, if you try `Asset.first.attachable` then you will get `uninitialized constant Attachable`. For some reason it isn't realizing that it should be fetching a `Note` instead of an `Attachable`.

Works fine if you start with the `Note` and try to do a round-trip, i.e. `note.assets.first.attachable`.

**Comment by kuraga** [comment]
(after research)

Error appears in `sequel` 4.15.0

@jmay,
Do you have a solution?

**Comment by kuraga** [comment]
Error appears in `sequel` [4.15.0](https://github.com/jeremyevans/sequel/tree/4.15.0), [commit that causes this error](https://github.com/jeremyevans/sequel/commit/ae283c45550b999ad5cefa2dfff4da5c8ef1bb5c):
```
The only fallout from this change is that reciprocal_type for
many_to_one associations now needs access to the associated class
if not cached, so when caching is disabled, if there isn't a
single associated class (such as when using manually creating a
custom polymorphic association), you should manually set the
:reciprocal_type option.
```
