### ISSUE TITLE
Error if association is absent

### ISSUE THREAD

**Issue by kuraga** [jackdempsey/sequel_polymorphic#8]
Good day! We have
```ruby
:dataset => (proc do
  klass = constantize(send(:"#{able}_type"))
  klass.where(klass.primary_key => send(:"#{able}_id"))
end)
```
But an error will be thrown if association is absent (`send(:"#{able}_type").nil? && send(:"#{able}_id").nil?`).

In `:eager_loader` option's proc, similar.

Thanks!
/cc @jackdempsey @contentfree

**Comment by kuraga** [comment]
@jackdempsey @contentfree would you accept my patch for this?

**Comment by jackdempsey** [comment]
hi @kuraga,

Sure! I've added you as a collaborator as I don't use this personally any longer. Feel free to update as needed!

**Comment by kuraga** [comment]
@jackdempsey thanks! Watch please about my further requests like "push please to rubygems" :smile:

**Comment by kuraga** [comment]
(after research) Close as a duplicate of #7
