### ISSUE TITLE
Undefined method 'constantize' for Model

### ISSUE THREAD

**Issue by Draiken** [jackdempsey/sequel_polymorphic#9]
Hi there, I attempted to use this plugin and when I attempted to load a polymorphic association I get this error:

```
undefined method `constantize' for #<StorageItem:0x0000000175e080>
```

Which comes to this line: https://github.com/jackdempsey/sequel_polymorphic/blob/master/lib/sequel_polymorphic/sequel_polymorphic.rb#L34

I'm not sure if the method is unavailable inside the proc or if I need to configure some other extension on my Sequel.

For a quick fix I just added the `constantize(string)` method to the `Sequel::Model` class. Looking at the Sequel's source code, I found a `constantize` private instance method on the model's `Inflection` module, but my `Sequel::Model` does not seem to have it included. Any clues on how that could happen?

Here are the included modules on my `Sequel::Model`

```
2.1.5 :002 > Sequel::Model.included_modules
 => [Sequel::Plugins::Polymorphic::InstanceMethods, Sequel::Plugins::ActiveModel::InstanceMethods,
 Sequel::Plugins::Timestamps::InstanceMethods, Sequel::Model::Associations::InstanceMethods,
 Sequel::Model::InstanceMethods, Kernel]
```

And my initialization:

```
require 'sequel'
Sequel::Model.plugin :timestamps 
Sequel::Model.plugin :active_model 
Sequel::Model.plugin :polymorphic 
 
@@db = ::Sequel.connect(config.database) 
@@db.extension(:pagination)
```

The versions are: Sequel 4.24.0 and Sequel Polymorphic v0.2

Thanks for any help!

**Comment by Draiken** [comment]
When running `Sequel::Model.singleton_class.included_modules` the `Sequel::Inflections` module does show up... now I'm really confused :/

**Comment by kuraga** [comment]
@Draiken and what if to remove `@@db.extension(:pagination)`?

**Comment by Draiken** [comment]
Unfortunately nothing changes.

Did the context on which the `:dataset` proc runs change in recent versions? I'm just guessing since I haven't been following Sequel this closely

**Comment by kuraga** [comment]
@Draiken Unfortunately all tests are green wiith `4.24.0`. Can you please provide fuller code?

**Comment by nazipov** [comment]
I have the same problem. I changed code like `constantize(able_type)` to `able_type.constantize` include `Sequel.extension(:inflector)` and it's ok!

**Comment by kuraga** [comment]
@nazipov said:
> I have the same problem. I [changed](https://github.com/nazipov/sequel_polymorphic/commit/91dbe946a428050b185aee8bc2c547484dddee99) code likeconstantize(able_type) to able_type.constantize includeSequel.extension(:inflector) and it's ok!

**Comment by kuraga** [comment]
According to [code](https://github.com/jackdempsey/sequel_polymorphic/blob/master/lib/sequel_polymorphic/sequel_polymorphic.rb#L34), I don't understand why:
1) @jackdempsey used `self.constantize`, `self.singularize` but `String#capitalize`;
2) `self.constantize` doesn't work but `self.singularize` does.

**Comment by kuraga** [comment]
@Draiken @nazipov which version of Ruby do you use? Do you use Rails or ActiveSupport?

**Comment by Draiken** [comment]
I am not using rails, but I am using `activesupport (4.2.3)` and `activemodel (4.2.3)`.

Here are all my gems:
```
Gems included by the bundle:
  * activemodel (4.2.3)
  * activesupport (4.2.3)
  * builder (3.2.2)
  * bundler (1.10.3)
  * byebug (4.0.5)
  * columnize (0.9.0)
  * diff-lcs (1.2.5)
  * i18n (0.7.0)
  * json (1.8.3)
  * minitest (5.7.0)
  * pg (0.18.2)
  * rake (10.4.2)
  * rspec (3.3.0)
  * rspec-core (3.3.0)
  * rspec-expectations (3.3.0)
  * rspec-mocks (3.3.0)
  * rspec-support (3.3.0)
  * sequel (4.24.0)
  * sequel_polymorphic (0.2.0)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
```

**Comment by nazipov** [comment]
@kuraga My ruby version is `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`

**Comment by Draiken** [comment]
Oh, sorry... forgot the ruby version: `ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]`

**Comment by kuraga** [comment]
> According to code, I don't understand why self.constantize doesn't work but self.singularize does.
It's very strange, no?

What do you think about ActiveSupport/ActiveModel collision? Because they aren't used in tests which are green.

**Comment by nazipov** [comment]
@kuraga I don't use ActiveSupport/ActiveModel, but i have the same problem.

**Comment by Draiken** [comment]
It was the first thing I imagined to be the problem since ActiveSupport adds `constantize` to `String`, but I tried removing both of those gems and I still got the error. Looking at the code path the `constantize` method should be available when that proc runs, but for some reason it's not :/

I started a simple IRB env, required sequel and ran `Sequel::Model.new.send(:constantize)` and got `NoMethodError: undefined method `constantize' for #<Sequel::Model @values={}>`

So even without any dependencies, it seems the method is not there for me :(

**Comment by Draiken** [comment]
Interesting:
```
2.1.5 :007 > Sequel::Model.constantize
NoMethodError: private method `constantize' called for Sequel::Model:Class
	from (irb):7
	from /home/felipe/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by nazipov** [comment]
@kuraga May be you will try somethink like this `method(:constantize).source_location` ?

**Comment by kuraga** [comment]
@nazipov `["/home/sasha/sequel_polymorphic/vendor/bundle/ruby/2.2.0/gems/sequel-4.24.0/lib/sequel/model/inflections.rb", 121]`.

And you? `method(:singularize).source_location` ?

**Comment by kuraga** [comment]
> Interesting:
> 2.1.5 :007 > Sequel::Model.constantize

@Draiken it's [expected](https://github.com/jeremyevans/sequel/blob/54fa82326d3319d9aca4409c07f79edc09da3837/lib/sequel/model/inflections.rb#L108)

**Comment by nazipov** [comment]
> And you? method(:singularize).source_location ?
`NameError: undefined method 'singularize' for class 'Like'`

**Comment by kuraga** [comment]
Urgh... I need failing code. I don't know what to ask you more...

**Comment by nazipov** [comment]
@kuraga I will try share the code

**Comment by kuraga** [comment]
Thanks.

**Comment by nazipov** [comment]
@kuraga It's my code with mysql dump https://github.com/nazipov/debug_sequel_polymorphic

**Comment by Draiken** [comment]
@kuraga I know it's private, but I fixed the issue by adding an **instance method** `constantize` on `Sequel::Model`, but the private method was a **class method** on `Sequel::Model`.

If the `constantize` is a class method, shouldn't the proc call `self.class.constantize` instead?

Just guessing here, don't have time to test this out right now.

**Comment by kuraga** [comment]
@Draiken Yeah, you're completely right. And I confirm this on @nazipov 's [code](https://github.com/nazipov/debug_sequel_polymorphic): https://github.com/jackdempsey/sequel_polymorphic/commit/3ff24eeeb9f2033ce7c404005db9019f2b54998a.

Why all tests were green? They aren't full and many-to-one association tests are omit. I'm sorry I forgot about it cause I'm a new maintainer and there are new tests in plan.

I'll merge the fix with new tests.

Note: other calls like `constantize` are class-context (as I can see). We shouldn't change them.

**Comment by kuraga** [comment]
P.S. Can you propose a better fix? Because calling a private method isn't good.

**Comment by Draiken** [comment]
I don't see an easy way to do this cleanly. Since the Inflections module already declares those methods as private, it's hard to use that specific module.
The solutions I can think would involve either writing the methods ourselves, using alternatives (like `Kernel.const_get`) or having them on a separate module/class (still involves rewriting).

Honestly the inflections module is not the place for methods like `constantize` IMO, these should be isolated. Then we could use them without hacking our ways with a `send`. But that piece of code is on `Sequel`, so we can't change it easily :/

**Comment by Draiken** [comment]
That being said, I'd probably say the best way to go is to try extracting that piece of behavior from the `Inflections` module, or even making it public since we should never depend on private methods, try getting it merged on `Sequel`, then this can use the cool new methods :)

**Comment by kuraga** [comment]
Fixed via https://github.com/jackdempsey/sequel_polymorphic/commit/e35f52844295c315ade7f40620697da474b6e24c and `v0.2.1` published.

New test suite is still in progress. Totally new :smile:
